### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by kyuheejo** [denizlab/OAI-KL-Grade-Classification#1]
Hi, which OAI datasets did you use and how exactly should I set up data to run this code? (ex. pre-processing from Dicom, filename, folder name)

**Comment by suikei-wang** [comment]
Seconded. There are various OAI datasets: the baseline and OAI images in different months. Just wondering which one is used in this paper?

**Comment by cemmdeniz** [comment]
Hi, You can find the details on the data used in this work using OAI-KL-Grade-Classification/data/OAI_summary.csv file. In each row, there is a folder column that specifies images that are used for this work. You can also find specific columns for patientID, month of visit, KL grade and so on. Similarly, train/test/validation csv files also have this information.

**Comment by ghost** [comment]
I have requested to access data in the Osteoarthritis Initiative but it takes 2 months from now the website is still not working
can you please share the dataset?

**Comment by suikei-wang** [comment]
> I have requested to access data in the Osteoarthritis Initiative but it takes 2 months from now the website is still not working
> can you please share the dataset?

I don't think we can share the dataset privately as we signed the data use agreement for our own organization used only. They are under maintenance at the moment so you probably need to change another dataset.

**Comment by ghost** [comment]
Both MOST and this OAI Dataset are not available, my research thesis is kind of stuck due to this :( , Did you have this dataset or not?

**Comment by suikei-wang** [comment]
Even though we have this dataset, we cannot share it with you. You probably have to switch your research topic at this stage.

**Comment by ghost** [comment]
If I can request them about agreement to get data from your side., then if there is any possibility?

**Comment by suikei-wang** [comment]
Please contact the data provider directly. This is the only way you can access the data. Thanks. 
@cemmdeniz Could you please close this issue? As it still appears on my homepage and I have finished my topics on it.
