### ISSUE TITLE
Error while using  function evaluate.py 

### ISSUE THREAD

**Issue by ghost** [denizlab/OAI-KL-Grade-Classification#2]
Hi, when i run the code its gives this error , 

evaluate.py -lm ../model_weights/Classifier/best-model-baseline.pt -hp ../data/classifier/

OSError: Unable to open file (unable to open file: name = '../data/classifier/00m/9000798_00m_RIGHT_KNEE.hdf5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

**Comment by cemmdeniz** [comment]
you should have the "../data/classifier/00m/9000798_00m_RIGHT_KNEE.hdf5 file to use the python script.

**Comment by hammadyounas2008** [comment]
How to get 9000798_00m_RIGHT_KNEE.hdf5 this file?
